spring.application.name=enterprise-rag

# =========================
# OpenAI
# =========================
spring.ai.openai.apiKey=${OPENAI_API_KEY}


# =========================
# Qdrant
# =========================
spring.docker.compose.stop.command=down

spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=enterprise-rag


# =========================
# H2
# =========================
spring.datasource.url=jdbc:h2:mem:enterprise_ai
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=true

# H2 Console:
# http://localhost:8080/h2-console


# =========================
# MCP CLIENT
# =========================
spring.ai.mcp.client.enabled=true
spring.ai.mcp.client.name=enterprise-rag-mcp-client
spring.ai.mcp.client.version=1.0.0
spring.ai.mcp.client.type=SYNC

spring.ai.mcp.client.streamable-http.connections.local-mcp.url=http://localhost:8081
spring.ai.mcp.client.streamable-http.connections.local-mcp.endpoint=/mcp