spring.application.name=enterprise-rag
spring.ai.openai.apiKey=${OPENAI_API_KEY}

spring.docker.compose.stop.command=down

spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=enterprise-rag

spring.datasource.url=jdbc:h2:mem:enterprise_ai
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=true
#http://localhost:8080/h2-console : used to login to H2 DB Console
