spring.application.name=enterprise-rag
spring.ai.openai.apiKey=${OPENAI_API_KEY}

spring.docker.compose.stop.command=down

spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=enterprise-rag
